#pragma once

#include <juce_graphics/juce_graphics.h>

// OscillaFX butterfly artwork, decoded once from the PNG bytes in BrandAssets.h
// (generated by assets/brand/make_logo.py).
namespace Brand
{
    // Teal phosphor mark with glow, transparent background.
    const juce::Image& mark();

    // 40 px black template silhouette for the menu bar (alpha only).
    const juce::Image& trayGlyph();
}
